//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashRegister()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int CashRegisterID { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public decimal InitialBalance { get; set; }
        public Nullable<decimal> FinalBalance { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public Nullable<decimal> CashierAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
