//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Product_Order = new HashSet<Product_Order>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<int> PersonalID { get; set; }
        public Nullable<int> IDDelivery { get; set; }
        public Nullable<int> IDState { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual ICollection<Product_Order> Product_Order { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
