//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Product_Order = new HashSet<Product_Order>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsPrepared { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Status { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Product_Order> Product_Order { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
