//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeSupply
    {
        public int RecipeSupplyID { get; set; }
        public int RecipeID { get; set; }
        public int SupplyID { get; set; }
        public decimal UseQuantity { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
