//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder_Supply
    {
        public int SupplierOrderID { get; set; }
        public int SupplyID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total { get; set; }
    
        public virtual Supply Supply { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
    }
}
