//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order
    {
        public int SupplierID { get; set; }
        public int SupplyID { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
        public string OrderFolio { get; set; }
        public decimal Total { get; set; }
        public decimal Quantity { get; set; }
        public string Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
