//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order
    {
        public int SupplierID { get; set; }
        public int SupplyID { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
        public string OrderFolio { get; set; }
        public decimal Total { get; set; }
        public decimal Quantity { get; set; }
        public string Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
