//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierOrder()
        {
            this.SupplierOrder_Supply = new HashSet<SupplierOrder_Supply>();
        }
    
        public int SupplierOrderID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
        public string OrderFolio { get; set; }
        public decimal Total { get; set; }
        public string Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrder_Supply> SupplierOrder_Supply { get; set; }
    }
}
