//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyCategory
    {
        public SupplyCategory()
        {
            this.StockReports = new HashSet<StockReport>();
            this.Supplies = new HashSet<Supply>();
        }
    
        public int SupplyCategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<StockReport> StockReports { get; set; }
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
