//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
            this.Supplier_Order = new HashSet<Supplier_Order>();
            this.Supplies = new HashSet<Supply>();
        }
    
        public int SupplierID { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactName { get; set; }
        public int CategorySupply { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Supplier_Order> Supplier_Order { get; set; }
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
