//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.WasteSupplies = new HashSet<WasteSupply>();
            this.SupplierOrder_Supply = new HashSet<SupplierOrder_Supply>();
        }
    
        public int SupplyID { get; set; }
        public string SupplyName { get; set; }
        public string Brand { get; set; }
        public int SupplyCategoryID { get; set; }
        public decimal Stock { get; set; }
        public int SupplierID { get; set; }
        public decimal Price { get; set; }
        public string MeasureUnit { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual SupplyCategory SupplyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WasteSupply> WasteSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrder_Supply> SupplierOrder_Supply { get; set; }
    }
}
