//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.RecipeSupplies = new HashSet<RecipeSupply>();
            this.SupplierOrder_Supply = new HashSet<SupplierOrder_Supply>();
            this.WasteSupplies = new HashSet<WasteSupply>();
        }
    
        public int SupplyID { get; set; }
        public string SupplyName { get; set; }
        public string Brand { get; set; }
        public int SupplyCategoryID { get; set; }
        public decimal Stock { get; set; }
        public int SupplierID { get; set; }
        public decimal Price { get; set; }
        public string MeasureUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeSupply> RecipeSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOrder_Supply> SupplierOrder_Supply { get; set; }
        public virtual SupplyCategory SupplyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WasteSupply> WasteSupplies { get; set; }
    }
}
