//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public Supply()
        {
            this.Supplier_Order = new HashSet<Supplier_Order>();
            this.WasteSupplies = new HashSet<WasteSupply>();
        }
    
        public int SupplyID { get; set; }
        public string SupplyName { get; set; }
        public string Brand { get; set; }
        public int SupplyCategoryID { get; set; }
        public decimal Stock { get; set; }
        public int SupplierID { get; set; }
        public decimal Price { get; set; }
        public string MeasureUnit { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Supplier_Order> Supplier_Order { get; set; }
        public virtual SupplyCategory SupplyCategory { get; set; }
        public virtual ICollection<WasteSupply> WasteSupplies { get; set; }
    }
}
