//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string FinancialFlow { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int CashRegisterID { get; set; }
        public Nullable<int> SupplierOrderID { get; set; }
        public int Concept { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual SupplierOrder SupplierOrder { get; set; }
        public virtual CashRegister CashRegister { get; set; }
    }
}
