//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteSupply
    {
        public int WasteID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int SupplyID { get; set; }
    
        public virtual Supply Supply { get; set; }
    }
}
